### ISSUE TITLE
Review teamwork process to avoid conflicts and document in README

### ISSUE THREAD

**Issue by patrickwalkowicz** [codingforeveryone/js#21]
@JMurphyWeb, @Bektaz I've done some reasearch on GitHub workflows inspired by our recent conversation and [this](https://github.com/codingforeveryone/js/pull/18#issuecomment-143412417) comment.

I've found a good article on [GitHub Flow](http://scottchacon.com/2011/08/31/github-flow.html).

So after reading that, I have a few ideas.
1. We could abandon working on our own forks and switch to working on codingforeveryone/js directly (as we all have rights to push changes - it's been probably setup this way by @Bektaz while creating the repo, is that correct?)
2. For each new challenge, the author would create a new branch named after the function and create an issue describing the challenge.
3. If any of us wants to take the challenge, we can reply to the issue so the rest of us won't try to push their solutions at the same time. So in a sense this person would 'reserve' a spot for solving the problem.
4. When a solution is ready, the changes can be pushed to the *branch named after the challenge* and then, a pull request created (from that branch to master). So even if the solution isn't correct, it won't be pushed to master branch yet and can be corrected easily.
5. If the person who created the challenge decides that the solution is correct, he/she can merge the pull request into the master.

Please let me know if that makes sense and if anything can be improved?

**Comment by Bektaz** [comment]
@patrickwalkowicz excellent job :+1: you put in order our workflow and hopefully we can get rid of the problem about pull request conflict which occures from time to time.

With your permission let me add some points to your proposal

1. It is true we all have rights to work by creating branches inside this repo and forking this repo.
My opinion here is let other users to choose which way they would like to work with. I mean as this repo for mastering our skills in github as well it would be better to leave the option to work with fork as well and it would be a good practise too. 
Just one main point to keep in mind is every contributor should be responsible for the pull request they create and make sure it does not have any conflict with upstream repo (in our case this repo). As I understood from documentation it is possible by synchronizing the fork repo with upstream one. I included in README.md file the link where steps to work with fork repo  described including synchronization.

2. I totally agree with you here.

3. In addition to your suggestion I would like to put into discussion the way of being involved in our activity. If person who opens an issue assigns the issue to other person and that person who have been assigned completes the issue he will create another issue and assigns it to next person. In this way we would circulate among contributors and make sure that everybody is involved and getting experience. If adressed person can't solve the issue then the author could put it into discussion with additional comment and pick first contributor who proposes his solution and assign it to him. But the order of people in circle will not be destroyed and will remain always steady (we need to define the order). Otherwise I noticed because of time difference not all of us can contribute to the issue at once. 

These changes I wanted to add to your proposal, thanks a lot for you offer @patrickwalkowicz  and @JMurphyWeb, @thevalent, @daymos  lets share with your thoughts related to this discussion 

I open my proposal about changes in README.md as a request (from fork because I wanted to get experiance with fork :smile: ) and let you have a look, comment etc.

**Comment by daymos** [comment]
Hi @patrickwalckowicz, @bektaz, and all others. 
I agree on the general solution proposed  by patrick. Creating a new branch for each new challenge seems a tidier solution. 
Regarding forking,  it seems that the current solution is commonly used on github. So leaving the choice to the proponent seems, good. I certainly would like to create a challenge using the 2 methods, to see from that perspective how it works  in both ways.

Regarding point 3, on who takes a challenge, in theory I like the solution proposed by bektaz but I am not sure if it is feasible. I think it is clear to us that it take some time and energy to solve a challenge. So one needs to use  some of his  free time, which for some  might be  available in a "discontinued fashion", so to speak. The current solution, while imperfect, allows people to take part when they have time. So I like the solution proposed by patrick of "researvinq" the first answer.

**Comment by patrickwalkowicz** [comment]
Thanks for your input, guys!
@Bektaz, regarding what you've suggested:

1. I like the idea of doing things either way just for the sake of learning. As long as the person contributing makes sure his fork is up to date before creating a pull request, we'll be fine. 
From what I've seen the method of creating a pull request from a fork is used mostly in open-source projects when there's a couple of project leaders and anybody can contribute. On the other hand, using the main repo directly seems to be a more popular solution within companies (it just makes more sense to do it this way). So learning to do things both ways would be very useful.

3. I like the idea of picking the next person to solve a challenge very much. I think it's great as a source of additional motivation and even if you're not sure how to solve a hypothetical challenge, you're much more likely to stick to it no matter what until it's solved (because you don't want to leave it publicly unsolved, right? :smile: ). However, I agree with @daymos that the amount of time available for each of us might be different so I think that we should stick to the system of volunteering to create challenges/solutions. This time we can all use our time more optimally. Both solutions have their strong and weak spots but I think the original one makes more sense at this point.

**Comment by Bektaz** [comment]
Hi guys!

@patrickwalkowicz , @daymos thanks for active discussion I agree with you. So now we have more or less the general opinion of our contributors and of course I am up to it too :smile:

**Comment by daymos** [comment]
yes, this is very useful. Im glad to be part of this group!

**Comment by JMurphyWeb** [comment]
Hey all, I like the points put forward, for now i will try to learn the
branching method before complicating things with the fork again!

I have just opened an issue with an idea that would ensure there is always
a new problem waiting for any new member, please take a look.

I don't know if I only speak for myself, but right now my main aim from
this repo is to grow comfortable with GitHub (codewars has plenty of
difficult JS challenges to occupy me with!)  In order to achieve this there
needs to be a constant stream of problems that are waiting to be solved.
Of course we all have other things to be getting on with, so in order to
keep this fantastic repo going strong, perhaps we could always aim to have
at least 1 exercise open at any given time?

This needn't take much time, here are some ideas to ensure we can keep a
number of problems available for the minimum amount of time:
* Create your own super easy problems  -  naturally those who begin to feel
comfortable with GitHub will generally leave these alone
* Copy problems from project euler https://projecteuler.net/
* Copy problems from Codewars

Let me know your thoughts. Cheers.
