### ISSUE TITLE
New Member #3 - alternating string

### ISSUE THREAD

**Issue by andrewMacmurray** [codingforeveryone/js#35]
#### Have a look through the readme before completing it
-
Write a function that takes a size and returns a string of alternating '1s' and '0s'.

the string should start with a 1.

a string with size 6 should return :  `'101010'`

with size 4 should return : `'1010'`

with size 12 should return : `'101010101010'`

The size will take positive whole numbers.

**Comment by AaronSlawson** [comment]
```javascript
function alternateString(size){
	var num = ""
	
	for (var i = 0; i < size; i++){
		if (num.slice(-1) === "1"){
			num = num.concat("0");
		}
		else{
			num = num.concat("1");
		}
	}
	
	return num;
	
}
```

Not sure what the proper way to submit answers to an issue is (first day on github) but here is mine.

**Comment by toast565** [comment]
Hi @AaronSlawson. Answer looks good - I didn't know you could use minus numbers with slice! 

Can you submit the answer in a new folder in the codingforeveryone/js repo. It should have a readme with @andrewMacmurray's instructions, and a js file with your solution, like in [this folder](https://github.com/codingforeveryone/js/tree/master/splitBills). Here's a [good guide to git](https://github.com/NataliaLKB/learn-git-basics) to help you.

Also can you think up and post a 'New Member #4' problem as a new issue so that the next new member has something to learn git with on? Cheers! :)

**Comment by andrewMacmurray** [comment]
@AaronSlawson great! Interesting solution with the slice(-1)

@toast565 file structure looks much better now

**Comment by Katbow** [comment]
Closing issue as [a solution has been committed](https://github.com/codingforeveryone/js/blob/master/New%20Member%20Problems/New%20member%20%233%20-%20alternateString/alternateString.js).
