### ISSUE TITLE
Add readme and description to this repo

### ISSUE THREAD

**Issue by iteles** [codingforeveryone/js#4]
Hi @Bektaz,

You created this `js` repo in the codingforeveryone organisation rather than on your personal account which we  take to mean that this is a resource for the whole community to benefit from :tada: :clap: 

Could you please add both a _description_ and a _readme_ to the repo so that **everyone may understand what the repo is about and how it should be used**?

Thank you again for taking part in the _codingforeveryone community_ !

**Comment by Bektaz** [comment]
Hi @iteles,

I added description and README.md file. Can you have a look please?
Thanks!

**Comment by iteles** [comment]
@Bektaz So it's a repo where people can post Javascript problems in order to practice their Javascript skills?

**Comment by Bektaz** [comment]
@iteles,

Exactly

**Comment by micklondon** [comment]
Hello coding for everyone,

I signed up for the course but wasn't selected I do however get mails from
students.

On Wed, 16 Sep 2015 14:51 Bektaz <notifications@github.com> wrote:

> @iteles <https://github.com/iteles>,
>
> Exactly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codingforeveryone/js/issues/4#issuecomment-140732356>.
>
-- 
Mick Pedroli.
69 Wisteria Apartments
33-43 Chatham Place
London  E9 6FB
078 77 11 88 93

**Comment by nelsonic** [comment]
@micklondon be *careful* about sharing enough ***personal information*** for someone to "borrow" your identity on the internet ... (*I highly recommend you edit that last comment to remove your home address and mobile phone number...*)

You are receiving these emails because we *very much* want you to be a part of the **codingforeveryone** ***community*** (*which is a big decision factor in the Founders & Coders selection criteria. :wink: 

If you prefer not to receive the emails, simply un-subscribe by "un-watching" this (or any other GitHub) repository at the top of this page.

**Comment by iteles** [comment]
@Bektaz Thanks for clarifying, issue closed! :blush:
